"""Small UPnP port-forwarding helper.

Discovery and SOAP request shape are based on gryphius/port-forward:
https://github.com/gryphius/port-forward.git
"""

import http.client
import re
import socket
import sys
import time
import urllib.request
from urllib.parse import urlparse
from xml.dom.minidom import Document, parseString


# Return UPnP Internet Gateway Device description URLs visible on the LAN.
def discover():
    ssdp_addr = "239.255.255.250"
    ssdp_port = 1900
    ssdp_request = (
        "M-SEARCH * HTTP/1.1\r\n"
        f"HOST: {ssdp_addr}:{ssdp_port}\r\n"
        'MAN: "ssdp:discover"\r\n'
        "MX: 2\r\n"
        "ST: urn:schemas-upnp-org:device:InternetGatewayDevice:1\r\n\r\n"
    )

    paths = []
    with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as sock:
        sock.setblocking(False)
        sock.sendto(ssdp_request.encode(), (ssdp_addr, ssdp_port))
        time.sleep(1)
        for _ in range(10):
            try:
                data, _fromaddr = sock.recvfrom(1024)
            except OSError:
                break
            headers = re.findall(r'(?P<name>.*?): (?P<value>.*?)\r\n', data.decode("utf-8"))
            locations = [value for name, value in headers if name.lower() == "location"]
            if locations:
                paths.append(locations[0])
    return paths


# Return the WANIPConnection control path from a UPnP device description.
def get_wanip_path(upnp_url):
    directory = urllib.request.urlopen(upnp_url).read()
    service_types = parseString(directory).getElementsByTagName('serviceType')
    for service in service_types:
        if service.childNodes[0].data.find('WANIPConnection') > 0:
            return service.parentNode.getElementsByTagName('controlURL')[0].childNodes[0].data
    return None


# Send a WANIPConnection AddPortMapping request.
def open_port(
    service_url,
    external_port,
    internal_client,
    internal_port=None,
    protocol='TCP',
    duration=0,
    description=None,
    enabled=1,
):
    parsed_url = urlparse(service_url)
    internal_port = external_port if internal_port is None else internal_port
    description = description or 'generated by port-forward.py'
    duration = 1 if not enabled else duration

    doc = Document()
    envelope = doc.createElementNS('', 's:Envelope')
    envelope.setAttribute('xmlns:s', 'http://schemas.xmlsoap.org/soap/envelope/')
    envelope.setAttribute('s:encodingStyle', 'http://schemas.xmlsoap.org/soap/encoding/')
    body = doc.createElementNS('', 's:Body')
    action = doc.createElementNS('', 'u:AddPortMapping')
    action.setAttribute('xmlns:u', 'urn:schemas-upnp-org:service:WANIPConnection:1')

    arguments = [
        ('NewRemoteHost', ""),
        ('NewExternalPort', external_port),
        ('NewProtocol', protocol),
        ('NewInternalPort', internal_port),
        ('NewInternalClient', internal_client),
        ('NewEnabled', enabled),
        ('NewPortMappingDescription', description),
        ('NewLeaseDuration', duration),
    ]
    for key, value in arguments:
        node = doc.createElement(key)
        node.appendChild(doc.createTextNode(str(value)))
        action.appendChild(node)

    body.appendChild(action)
    envelope.appendChild(body)
    doc.appendChild(envelope)

    conn = http.client.HTTPConnection(parsed_url.hostname, parsed_url.port)
    conn.request(
        'POST',
        parsed_url.path,
        doc.toxml(),
        {
            'SOAPAction': '"urn:schemas-upnp-org:service:WANIPConnection:1#AddPortMapping"',
            'Content-Type': 'text/xml',
        },
    )
    response = conn.getresponse()
    return response.status, response.read()


# Return the local address used to reach routerip.
def get_my_ip(routerip=None):
    routerip = routerip or "8.8.8.8"
    try:
        with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as sock:
            sock.connect((routerip, 80))
            return sock.getsockname()[0]
    except OSError:
        return None


# Discover routers and request a port mapping on matching devices.
def forwardPort(eport, iport, router, lanip, disable, protocol, time, description, verbose):
    if verbose:
        print("Discovering routers...")

    for path in discover():
        discovered = urlparse(path)
        service_path = get_wanip_path(path)
        if not service_path:
            continue
        service_url = f"{discovered.scheme}://{discovered.netloc}{service_path}"
        routerip = discovered.netloc.split(':')[0]
        if router is not None and routerip not in router:
            continue

        localip = lanip or get_my_ip(routerip)
        enabled = int(not disable)
        prefix = '' if enabled else 'disable of '
        status, message = open_port(
            service_url,
            eport,
            internal_client=localip,
            internal_port=iport,
            protocol=protocol,
            duration=time,
            description=description,
            enabled=enabled,
        )
        if status == 200:
            if verbose:
                print(f"{prefix}port forward on {routerip} successful, {eport}->{localip}:{iport}")
        else:
            sys.stderr.write(
                f"{prefix}port forward on {routerip} failed, status={status} message={message}\n"
            )

    return
